export const summer_2023_cosmetic_case = {
    item_count: 25, // Including the Exceedingly Rare Special Item
    items: [
        {
            id: 1,
            name: 'Stealth Bomber',
            grade: 1,
            cumulative_drop_rate: 0.08,
            img: 'https://wiki.teamfortress.com/w/images/1/13/Backpack_Stealth_Bomber.png',
            unusual: 0,
        },
        {
            id: 2,
            name: "Le Professionnel",
            grade: 1,
            cumulative_drop_rate: 0.16,
            img: 'https://wiki.teamfortress.com/w/images/0/0b/Backpack_Le_Professionnel.png',
            unusual: 0,
        },
        {
            id: 3,
            name: 'Cargo Constructor',
            grade: 1,
            cumulative_drop_rate: 0.24,
            img: 'https://wiki.teamfortress.com/w/images/a/ac/Backpack_Cargo_Constructor.png',
            unusual: 0,
        },
        {
            id: 4,
            name: 'Blast Bowl',
            grade: 1,
            cumulative_drop_rate: 0.32,
            img: 'https://wiki.teamfortress.com/w/images/9/9d/Backpack_Blast_Bowl.png',
            unusual: 1,
        },
        {
            id: 5,
            name: 'Heavy Metal',
            grade: 1,
            cumulative_drop_rate: 0.40,
            img: 'https://wiki.teamfortress.com/w/images/1/1a/Backpack_Heavy_Metal.png',
            unusual: 0,
        },
        {
            id: 6,
            name: 'Brimmed Bootlegger',
            grade: 1,
            cumulative_drop_rate: 0.48,
            img: 'https://wiki.teamfortress.com/w/images/a/a4/Backpack_Brimmed_Bootlegger.png',
            unusual: 1,
        },
        {
            id: 7,
            name: 'Medical Emergency',
            grade: 1,
            cumulative_drop_rate: 0.56,
            img: 'https://wiki.teamfortress.com/w/images/c/c8/Backpack_Medical_Emergency.png',
            unusual: 0,
        },
        {
            id: 8,
            name: 'Bushman',
            grade: 1,
            cumulative_drop_rate: 0.64,
            img: 'https://wiki.teamfortress.com/w/images/5/56/Backpack_Bushman.png',
            unusual: 0,
        },
        {
            id: 9,
            name: "Firestalker",
            grade: 1,
            cumulative_drop_rate: 0.72,
            img: 'https://wiki.teamfortress.com/w/images/c/cf/Backpack_Firestalker.png',
            unusual: 1,
        },
        {
            id: 10,
            name: 'Brothers in Blues',
            grade: 1,
            cumulative_drop_rate: 0.80,
            img: 'https://wiki.teamfortress.com/w/images/a/a9/Backpack_Brothers_in_Blues.png',
            unusual: 1,
        },
        {
            id: 11,
            name: 'Prohibition Opposition',
            grade: 2,
            cumulative_drop_rate: 0.82,
            img: 'https://wiki.teamfortress.com/w/images/5/57/Backpack_Prohibition_Opposition.png',
            unusual: 0,
        },
        {
            id: 12,
            name: "Preventative Measure",
            grade: 2,
            cumulative_drop_rate: 0.84,
            img: 'https://wiki.teamfortress.com/w/images/thumb/d/db/Backpack_Preventative_Measure.png/90px-Backpack_Preventative_Measure.png',
            unusual: 0,
        },
        {
            id: 13,
            name: 'Hazard Handler',
            grade: 2,
            cumulative_drop_rate: 0.86,
            img: 'https://wiki.teamfortress.com/w/images/0/06/Backpack_Hazard_Handler.png',
            unusual: 1,
        },
        {
            id: 14,
            name: 'Soho Sleuth',
            grade: 2,
            cumulative_drop_rate: 0.88,
            img: 'https://wiki.teamfortress.com/w/images/1/1c/Backpack_Soho_Sleuth.png',
            unusual: 1,
        },
        {
            id: 15,
            name: 'Close Quarters Cover',
            grade: 2,
            cumulative_drop_rate: 0.90,
            img: 'https://wiki.teamfortress.com/w/images/5/5f/Backpack_Close_Quarters_Cover.png',
            unusual: 1,
        },
        {
            id: 16,
            name: 'Hog Heels',
            grade: 2,
            cumulative_drop_rate: 0.92,
            img: 'https://wiki.teamfortress.com/w/images/d/de/Backpack_Hog_Heels.png',
            unusual: 0,
        },
        {
            id: 17,
            name: 'Shrapnel Shell',
            grade: 2,
            cumulative_drop_rate: 0.94,
            img: 'https://wiki.teamfortress.com/w/images/2/22/Backpack_Shrapnel_Shell.png',
            unusual: 0,
        },
        {
            id: 18,
            name: 'Cleaner\'s Cap',
            grade: 2,
            cumulative_drop_rate: 0.96,
            img: 'https://wiki.teamfortress.com/w/images/6/6e/Backpack_Cleaner%27s_Cap.png',
            unusual: 1,
        },
        {
            id: 19,
            name: 'Brother Mann',
            grade: 3,
            cumulative_drop_rate: 0.9648,
            img: 'https://wiki.teamfortress.com/w/images/5/56/Backpack_Brother_Mann.png',
            unusual: 0,
        },
        {
            id: 20,
            name: 'Cranium Cover',
            grade: 3,
            cumulative_drop_rate: 0.969,
            img: 'https://wiki.teamfortress.com/w/images/1/12/Backpack_Cranium_Cover.png',
            unusual: 1,
        },
        {
            id: 21,
            name: 'Über-Wear',
            grade: 3,
            cumulative_drop_rate: 0.9732,
            img: 'https://wiki.teamfortress.com/w/images/6/61/Backpack_%C3%9Cber-Wear.png',
            unusual: 0,
        },
        {
            id: 22,
            name: "Flame Warrior",
            grade: 3,
            cumulative_drop_rate: 0.9774,
            img: 'https://wiki.teamfortress.com/w/images/6/67/Backpack_Flame_Warrior.png',
            unusual: 1,
        },
        {
            id: 23,
            name: "Glorious Gambeson",
            grade: 3,
            cumulative_drop_rate: 0.9816,
            img: 'https://wiki.teamfortress.com/w/images/5/50/Backpack_Glorious_Gambeson.png',
            unusual: 0,
        },
        {
            id: 24,
            name: "Full Metal Helmet",
            grade: 4,
            cumulative_drop_rate: 0.9858,
            img: 'https://wiki.teamfortress.com/w/images/8/81/Backpack_Full_Metal_Helmet.png',
            unusual: 1,
        },
        {
            id: 25,
            name: "Cranium Cooler",
            grade: 4,
            cumulative_drop_rate: .99,
            img: 'https://wiki.teamfortress.com/w/images/5/54/Backpack_Cranium_Cooler.png',
            unusual: 1,
        },
    ]
};

export const winter_2023_cosmetic_case = {
    item_count: 23, // Including the Exceedingly Rare Special Item
    items: [
        {
            id: 1,
            name: 'Bigger Mann on Campus',
            grade: 1,
            cumulative_drop_rate: 0.08,
            img: 'https://wiki.teamfortress.com/w/images/3/34/Backpack_Bigger_Mann_on_Campus.png',
            unusual: 0,
        },
        {
            id: 2,
            name: "Balkan's Brute",
            grade: 1,
            cumulative_drop_rate: 0.16,
            img: 'https://wiki.teamfortress.com/w/images/7/77/Backpack_Balkan%27s_Brute.png',
            unusual: 1,
        },
        {
            id: 3,
            name: 'Impact Impaler',
            grade: 1,
            cumulative_drop_rate: 0.24,
            img: 'https://wiki.teamfortress.com/w/images/d/d7/Backpack_Impact_Impaler.png',
            unusual: 1,
        },
        {
            id: 4,
            name: 'Rugged Rags',
            grade: 1,
            cumulative_drop_rate: 0.32,
            img: 'https://wiki.teamfortress.com/w/images/6/64/Backpack_Rugged_Rags.png',
            unusual: 0,
        },
        {
            id: 5,
            name: 'Covert Covers',
            grade: 1,
            cumulative_drop_rate: 0.40,
            img: 'https://wiki.teamfortress.com/w/images/c/c7/Backpack_Covert_Covers.png',
            unusual: 1,
        },
        {
            id: 6,
            name: 'Sleuth Suit',
            grade: 1,
            cumulative_drop_rate: 0.48,
            img: 'https://wiki.teamfortress.com/w/images/0/04/Backpack_Sleuth_Suit.png',
            unusual: 0,
        },
        {
            id: 7,
            name: 'Nightcap',
            grade: 1,
            cumulative_drop_rate: 0.56,
            img: 'https://wiki.teamfortress.com/w/images/4/48/Backpack_Nightcap.png',
            unusual: 1,
        },
        {
            id: 8,
            name: 'Puffed Practitioner',
            grade: 1,
            cumulative_drop_rate: 0.64,
            img: 'https://wiki.teamfortress.com/w/images/9/93/Backpack_Puffed_Practitioner.png',
            unusual: 0,
        },
        {
            id: 9,
            name: "Wanderer's Wool",
            grade: 1,
            cumulative_drop_rate: 0.72,
            img: 'https://wiki.teamfortress.com/w/images/5/56/Backpack_Wanderer%27s_Wool.png',
            unusual: 1,
        },
        {
            id: 10,
            name: 'Cozy Cover-Up',
            grade: 1,
            cumulative_drop_rate: 0.80,
            img: 'https://wiki.teamfortress.com/w/images/f/f8/Backpack_Cozy_Cover-Up.png',
            unusual: 0,
        },
        {
            id: 11,
            name: 'Isotopic Insulator',
            grade: 2,
            cumulative_drop_rate: 0.825,
            img: 'https://wiki.teamfortress.com/w/images/0/08/Backpack_Isotopic_Insulator.png',
            unusual: 0,
        },
        {
            id: 12,
            name: "Torcher's Trench Coat",
            grade: 2,
            cumulative_drop_rate: 0.8475,
            img: 'https://wiki.teamfortress.com/w/images/1/19/Backpack_Torcher%27s_Trench_Coat.png',
            unusual: 0,
        },
        {
            id: 13,
            name: 'Strasbourg Scholar',
            grade: 2,
            cumulative_drop_rate: 0.87,
            img: 'https://wiki.teamfortress.com/w/images/5/5f/Backpack_Strasbourg_Scholar.png',
            unusual: 0,
        },
        {
            id: 14,
            name: 'Clue Hairdo',
            grade: 2,
            cumulative_drop_rate: 0.8925,
            img: 'https://wiki.teamfortress.com/w/images/9/98/Backpack_Clue_Hairdo.png',
            unusual: 1,
        },
        {
            id: 15,
            name: 'Slumber Slacks',
            grade: 2,
            cumulative_drop_rate: 0.915,
            img: 'https://wiki.teamfortress.com/w/images/6/69/Backpack_Slumber_Slacks.png',
            unusual: 0,
        },
        {
            id: 16,
            name: 'Frigid Fashion',
            grade: 2,
            cumulative_drop_rate: 0.9375,
            img: 'https://wiki.teamfortress.com/w/images/f/fe/Backpack_Frigid_Fashion.png',
            unusual: 1,
        },
        {
            id: 17,
            name: 'Trench Warfarer',
            grade: 2,
            cumulative_drop_rate: 0.95,
            img: 'https://wiki.teamfortress.com/w/images/2/20/Backpack_Trench_Warfarer.png',
            unusual: 0,
        },
        {
            id: 18,
            name: 'Dapper Dickens',
            grade: 3,
            cumulative_drop_rate: 0.958,
            img: 'https://wiki.teamfortress.com/w/images/4/4b/Backpack_Dapper_Dickens.png',
            unusual: 1,
        },
        {
            id: 19,
            name: 'Bonk Beanie',
            grade: 3,
            cumulative_drop_rate: 0.966,
            img: 'https://wiki.teamfortress.com/w/images/f/ff/Backpack_Bonk_Beanie.png',
            unusual: 0,
        },
        {
            id: 20,
            name: 'Masked Loyalty',
            grade: 3,
            cumulative_drop_rate: 0.974,
            img: 'https://wiki.teamfortress.com/w/images/8/85/Backpack_Masked_Loyalty.png',
            unusual: 0,
        },
        {
            id: 21,
            name: 'Lazy Lounger',
            grade: 3,
            cumulative_drop_rate: 0.982,
            img: 'https://wiki.teamfortress.com/w/images/e/e6/Backpack_Lazy_Lounger.png',
            unusual: 0,
        },
        {
            id: 22,
            name: "Boarder's Beanie",
            grade: 4,
            cumulative_drop_rate: 0.986,
            img: 'https://wiki.teamfortress.com/w/images/6/66/Backpack_Boarder%27s_Beanie.png',
            unusual: 0,
        },
        {
            id: 23,
            name: "Scruffed 'n Stitched",
            grade: 4,
            cumulative_drop_rate: 0.99,
            img: 'https://wiki.teamfortress.com/w/images/4/4d/Backpack_Scruffed_%27n_Stitched.png',
            unusual: 1,
        },
    ]
};
